theme: minima
title: Project Graffiti
description: A Project to collect and share datasets as well as publications in relation to machine learning in the context of printed products.
author: Josian MÃ¼ller